export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_MY_INFO = 'SET_MY_INFO'
export const DESTROY_ACCESS_TOKEN = 'DESTROY_ACCESS_TOKEN'
export const DESTROY_MY_INFO = 'DESTROY_MY_INFO'

export const FETCH_POST ='FETCH_POST'
export const UPLOAD_POST = 'UPLOAD_POST'
export const DELETE_POST = 'DELETE_POST'
